language: generic
os: osx
addons:
    homebrew:
        casks:
            - docker
before_install:
    - docker build -t texastoast/docker-react-test -f Dockerfile.dev .
script:
    - docker run -e CI=true texastoast/docker-react-test npm run test
